package ai.manifesto.codegen.runtime;

import java.time.Instant;

/**
 * KR: deterministic 기본값을 갖는 generated header 생성기입니다.
 * EN: Generated header builder with deterministic default behavior.
 */
public final class HeaderGenerator {
    private HeaderGenerator() {
    }

    public static String generateHeader(HeaderOptions options) {
        String source = options == null || options.sourceId() == null || options.sourceId().isBlank()
            ? "unknown"
            : options.sourceId();
        String schemaHash = options == null || options.schemaHash() == null || options.schemaHash().isBlank()
            ? "unknown"
            : options.schemaHash();

        StringBuilder builder = new StringBuilder();
        builder.append("// @generated by @manifesto-ai/codegen -- DO NOT EDIT\n");
        builder.append("// Source: ").append(source).append(" | Schema hash: ").append(schemaHash).append("\n");
        if (options != null && options.stamp()) {
            builder.append("// Generated at: ").append(Instant.now()).append("\n");
        }
        return builder.toString();
    }
}
