package ai.manifesto.codegen;

import ai.manifesto.codegen.runtime.*;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class CodegenRunnerIntegrationTest {

    @Test
    void generateDetailedAddsHeaderAndSchemaHashDeterministically() {
        CodegenRunner runner = CodegenRunner.withDefaults();
        CodegenRequest request = new CodegenRequest(
            Map.of("state", Map.of("fields", Map.of("name", Map.of("type", "string", "required", true)))),
            "ai.manifesto.generated",
            new CodegenTarget("java-dto", "1.0")
        );

        CodegenExecutionOptions options = new CodegenExecutionOptions(
            "schema://todo",
            false,
            true,
            CodegenPluginOptions.defaults()
        );

        CodegenRunResult first = runner.generateDetailed(request, options);
        CodegenRunResult second = runner.generateDetailed(request, options);

        assertFalse(first.hasErrors());
        assertEquals(first.schemaHash(), second.schemaHash());
        assertEquals(first.files(), second.files());
        assertTrue(first.files().get(0).content().startsWith("// @generated by @manifesto-ai/codegen"));
        assertTrue(first.files().get(0).content().contains("Schema hash: " + first.schemaHash()));
    }

    @Test
    void generateDetailedReportsCollisionsAndBlocksSuccess() {
        CodegenPlugin collidingPlugin = new CodegenPlugin() {
            @Override
            public String pluginId() {
                return "collision-plugin";
            }

            @Override
            public boolean supports(CodegenTarget target) {
                return "collision-target".equals(target.name());
            }

            @Override
            public List<GeneratedArtifact> generate(CodegenRequest request) {
                return List.of(
                    new GeneratedArtifact("same/File.java", "class A {}"),
                    new GeneratedArtifact("same/File.java", "class B {}")
                );
            }
        };

        CodegenRunner runner = new CodegenRunner(new CodegenPluginRegistry().register(collidingPlugin));
        CodegenRequest request = new CodegenRequest(
            Map.of("state", Map.of("fields", Map.of("id", Map.of("type", "string")))),
            "ai.manifesto.generated",
            new CodegenTarget("collision-target", "1.0")
        );

        CodegenRunResult result = runner.generateDetailed(request, CodegenExecutionOptions.defaults());
        assertTrue(result.hasErrors());
        assertTrue(result.diagnostics().stream().anyMatch(d -> d.level() == CodegenDiagnosticLevel.ERROR));

        assertThrows(IllegalStateException.class, () -> runner.generate(request));
    }

    @Test
    void generateDetailedValidatesPluginOptions() {
        CodegenRunner runner = CodegenRunner.withDefaults();
        CodegenRequest request = new CodegenRequest(
            Map.of("state", Map.of("fields", Map.of("name", Map.of("type", "string")))),
            "ai.manifesto.generated",
            new CodegenTarget("java-dto", "1.0")
        );

        CodegenExecutionOptions invalidOptions = new CodegenExecutionOptions(
            "source://x",
            false,
            true,
            new CodegenPluginOptions(null, NullabilityMode.STRICT, StyleProfile.STANDARD)
        );

        CodegenRunResult result = runner.generateDetailed(request, invalidOptions);
        assertTrue(result.hasErrors());
        assertTrue(result.diagnostics().stream().anyMatch(d -> d.message().contains("naming")));
    }
}
